# Generated by Django 4.0.4 on 2022-05-19 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobp', '0011_alter_teacher_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='price',
            field=models.IntegerField(),
        ),
    ]
