# Generated by Django 4.0.4 on 2022-05-19 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobp', '0012_alter_teacher_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=60)),
            ],
        ),
    ]
