# Generated by Django 4.0.4 on 2022-05-20 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobp', '0013_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='location',
            field=models.CharField(blank=True, choices=[('01', 'Praha'), ('02', 'Stredocesky kraj'), ('03', 'Jihocesky kraj'), ('04', 'Plzensky kraj'), ('05', 'Karlovarsky kraj'), ('06', 'Ustecky kraj'), ('07', 'Liberecky kraj'), ('08', 'Kralovehradecky kraj'), ('09', 'Pardubicky kraj'), ('10', 'Vysocina'), ('11', 'Jihomorovsky kraj'), ('12', 'Zlinsky kraj'), ('13', 'Olomoucky kraj'), ('14', 'Moravskoslezsky kraj')], max_length=50, null=True),
        ),
    ]
